# Generated by Django 3.0.7 on 2020-06-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200624_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_pict',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
