# Generated by Django 3.0.7 on 2020-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_admin_profile_pict'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='alamat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
