# Generated by Django 3.0.7 on 2020-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200624_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penanganan',
            name='solusi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
