# Generated by Django 3.0.7 on 2020-08-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200714_1555'),
        ('pelayanan', '0010_chat_roomchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Admin'),
        ),
        migrations.AddField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Client'),
        ),
        migrations.DeleteModel(
            name='RoomChat',
        ),
    ]
