# Generated by Django 3.0.7 on 2020-08-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan', '0012_auto_20200803_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
