# Generated by Django 3.0.7 on 2020-08-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan', '0013_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
